WEB SCRAPPING PROJECT

In [18]:
# importing libraries
import pandas as pd
import requests as re
from bs4 import BeautifulSoup

In [8]:
# scrapping through website
page=re.get("https://www.worldometers.info/world-population/population-by-country/")

In [9]:
# Extracting data with the help of beautifulsoup
sp=BeautifulSoup(page.content)

In [10]:
table=sp.find_all("td")

In [11]:
# using for loop to add all the data in empty list 
list=[]
for i in table:
 list.append(i.text)
list

['1',
 'China',
 '1,439,323,776',
 '0.39 %',
 '5,540,090',
 '153',
 '9,388,211',
 '-348,399',
 '1.7',
 '38',
 '61 %',
 '18.47 %',
 '2',
 'India',
 '1,380,004,385',
 '0.99 %',
 '13,586,631',
 '464',
 '2,973,190',
 '-532,687',
 '2.2',
 '28',
 '35 %',
 '17.70 %',
 '3',
 'United States',
 '331,002,651',
 '0.59 %',
 '1,937,734',
 '36',
 '9,147,420',
 '954,806',
 '1.8',
 '38',
 '83 %',
 '4.25 %',
 '4',
 'Indonesia',
 '273,523,615',
 '1.07 %',
 '2,898,047',
 '151',
 '1,811,570',
 '-98,955',
 '2.3',
 '30',
 '56 %',
 '3.51 %',
 '5',
 'Pakistan',
 '220,892,340',
 '2.00 %',
 '4,327,022',
 '287',
 '770,880',
 '-233,379',
 '3.6',
 '23',
 '35 %',
 '2.83 %',
 '6',
 'Brazil',
 '212,559,417',
 '0.72 %',
 '1,509,890',
 '25',
 '8,358,140',
 '21,200',
 '1.7',
 '33',
 '88 %',
 '2.73 %',
 '7',
 'Nigeria',
 '206,139,589',
 '2.58 %',
 '5,175,990',
 '226',
 '910,770',
 '-60,000',
 '5.4',
 '18',
 '52 %',
 '2.64 %',
 '8',
 'Bangladesh',
 '164,689,383',
 '1.01 %',
 '1,643,222',
 '1,265',
 '130,170',
 '-369,501',
 '2.1',
 '28',
 '39 %',
 '2.11 %',
 '9',
 'Russia',
 '145,934,462',
 '0.04 %',
 '62,206',
 '9',
 '16,376,870',
 '182,456',
 '1.8',
 '40',
 '74 %',
 '1.87 %',
 '10',
 'Mexico',
 '128,932,753',
 '1.06 %',
 '1,357,224',
 '66',
 '1,943,950',
 '-60,000',
 '2.1',
 '29',
 '84 %',
 '1.65 %',
 '11',
 'Japan',
 '126,476,461',
 '-0.30 %',
 '-383,840',
 '347',
 '364,555',
 '71,560',
 '1.4',
 '48',
 '92 %',
 '1.62 %',
 '12',
 'Ethiopia',
 '114,963,588',
 '2.57 %',
 '2,884,858',
 '115',
 '1,000,000',
 '30,000',
 '4.3',
 '19',
 '21 %',
 '1.47 %',
 '13',
 'Philippines',
 '109,581,078',
 '1.35 %',
 '1,464,463',
 '368',
 '298,170',
 '-67,152',
 '2.6',
 '26',
 '47 %',
 '1.41 %',
 '14',
 'Egypt',
 '102,334,404',
 '1.94 %',
 '1,946,331',
 '103',
 '995,450',
 '-38,033',
 '3.3',
 '25',
 '43 %',
 '1.31 %',
 '15',
 'Vietnam',
 '97,338,579',
 '0.91 %',
 '876,473',
 '314',
 '310,070',
 '-80,000',
 '2.1',
 '32',
 '38 %',
 '1.25 %',
 '16',
 'DR Congo',
 '89,561,403',
 '3.19 %',
 '2,770,836',
 '40',
 '2,267,050',
 '23,861',
 '6.0',
 '17',
 '46 %',
 '1.15 %',
 '17',
 'Turkey',
 '84,339,067',
 '1.09 %',
 '909,452',
 '110',
 '769,630',
 '283,922',
 '2.1',
 '32',
 '76 %',
 '1.08 %',
 '18',
 'Iran',
 '83,992,949',
 '1.30 %',
 '1,079,043',
 '52',
 '1,628,550',
 '-55,000',
 '2.2',
 '32',
 '76 %',
 '1.08 %',
 '19',
 'Germany',
 '83,783,942',
 '0.32 %',
 '266,897',
 '240',
 '348,560',
 '543,822',
 '1.6',
 '46',
 '76 %',
 '1.07 %',
 '20',
 'Thailand',
 '69,799,978',
 '0.25 %',
 '174,396',
 '137',
 '510,890',
 '19,444',
 '1.5',
 '40',
 '51 %',
 '0.90 %',
 '21',
 'United Kingdom',
 '67,886,011',
 '0.53 %',
 '355,839',
 '281',
 '241,930',
 '260,650',
 '1.8',
 '40',
 '83 %',
 '0.87 %',
 '22',
 'France',
 '65,273,511',
 '0.22 %',
 '143,783',
 '119',
 '547,557',
 '36,527',
 '1.9',
 '42',
 '82 %',
 '0.84 %',
 '23',
 'Italy',
 '60,461,826',
 '-0.15 %',
 '-88,249',
 '206',
 '294,140',
 '148,943',
 '1.3',
 '47',
 '69 %',
 '0.78 %',
 '24',
 'Tanzania',
 '59,734,218',
 '2.98 %',
 '1,728,755',
 '67',
 '885,800',
 '-40,076',
 '4.9',
 '18',
 '37 %',
 '0.77 %',
 '25',
 'South Africa',
 '59,308,690',
 '1.28 %',
 '750,420',
 '49',
 '1,213,090',
 '145,405',
 '2.4',
 '28',
 '67 %',
 '0.76 %',
 '26',
 'Myanmar',
 '54,409,800',
 '0.67 %',
 '364,380',
 '83',
 '653,290',
 '-163,313',
 '2.2',
 '29',
 '31 %',
 '0.70 %',
 '27',
 'Kenya',
 '53,771,296',
 '2.28 %',
 '1,197,323',
 '94',
 '569,140',
 '-10,000',
 '3.5',
 '20',
 '28 %',
 '0.69 %',
 '28',
 'South Korea',
 '51,269,185',
 '0.09 %',
 '43,877',
 '527',
 '97,230',
 '11,731',
 '1.1',
 '44',
 '82 %',
 '0.66 %',
 '29',
 'Colombia',
 '50,882,891',
 '1.08 %',
 '543,448',
 '46',
 '1,109,500',
 '204,796',
 '1.8',
 '31',
 '80 %',
 '0.65 %',
 '30',
 'Spain',
 '46,754,778',
 '0.04 %',
 '18,002',
 '94',
 '498,800',
 '40,000',
 '1.3',
 '45',
 '80 %',
 '0.60 %',
 '31',
 'Uganda',
 '45,741,007',
 '3.32 %',
 '1,471,413',
 '229',
 '199,810',
 '168,694',
 '5.0',
 '17',
 '26 %',
 '0.59 %',
 '32',
 'Argentina',
 '45,195,774',
 '0.93 %',
 '415,097',
 '17',
 '2,736,690',
 '4,800',
 '2.3',
 '32',
 '93 %',
 '0.58 %',
 '33',
 'Algeria',
 '43,851,044',
 '1.85 %',
 '797,990',
 '18',
 '2,381,740',
 '-10,000',
 '3.1',
 '29',
 '73 %',
 '0.56 %',
 '34',
 'Sudan',
 '43,849,260',
 '2.42 %',
 '1,036,022',
 '25',
 '1,765,048',
 '-50,000',
 '4.4',
 '20',
 '35 %',
 '0.56 %',
 '35',
 'Ukraine',
 '43,733,762',
 '-0.59 %',
 '-259,876',
 '75',
 '579,320',
 '10,000',
 '1.4',
 '41',
 '69 %',
 '0.56 %',
 '36',
 'Iraq',
 '40,222,493',
 '2.32 %',
 '912,710',
 '93',
 '434,320',
 '7,834',
 '3.7',
 '21',
 '73 %',
 '0.52 %',
 '37',
 'Afghanistan',
 '38,928,346',
 '2.33 %',
 '886,592',
 '60',
 '652,860',
 '-62,920',
 '4.6',
 '18',
 '25 %',
 '0.50 %',
 '38',
 'Poland',
 '37,846,611',
 '-0.11 %',
 '-41,157',
 '124',
 '306,230',
 '-29,395',
 '1.4',
 '42',
 '60 %',
 '0.49 %',
 '39',
 'Canada',
 '37,742,154',
 '0.89 %',
 '331,107',
 '4',
 '9,093,510',
 '242,032',
 '1.5',
 '41',
 '81 %',
 '0.48 %',
 '40',
 'Morocco',
 '36,910,560',
 '1.20 %',
 '438,791',
 '83',
 '446,300',
 '-51,419',
 '2.4',
 '30',
 '64 %',
 '0.47 %',
 '41',
 'Saudi Arabia',
 '34,813,871',
 '1.59 %',
 '545,343',
 '16',
 '2,149,690',
 '134,979',
 '2.3',
 '32',
 '84 %',
 '0.45 %',
 '42',
 'Uzbekistan',
 '33,469,203',
 '1.48 %',
 '487,487',
 '79',
 '425,400',
 '-8,863',
 '2.4',
 '28',
 '50 %',
 '0.43 %',
 '43',
 'Peru',
 '32,971,854',
 '1.42 %',
 '461,401',
 '26',
 '1,280,000',
 '99,069',
 '2.3',
 '31',
 '79 %',
 '0.42 %',
 '44',
 'Angola',
 '32,866,272',
 '3.27 %',
 '1,040,977',
 '26',
 '1,246,700',
 '6,413',
 '5.6',
 '17',
 '67 %',
 '0.42 %',
 '45',
 'Malaysia',
 '32,365,999',
 '1.30 %',
 '416,222',
 '99',
 '328,550',
 '50,000',
 '2.0',
 '30',
 '78 %',
 '0.42 %',
 '46',
 'Mozambique',
 '31,255,435',
 '2.93 %',
 '889,399',
 '40',
 '786,380',
 '-5,000',
 '4.9',
 '18',
 '38 %',
 '0.40 %',
 '47',
 'Ghana',
 '31,072,940',
 '2.15 %',
 '655,084',
 '137',
 '227,540',
 '-10,000',
 '3.9',
 '22',
 '57 %',
 '0.40 %',
 '48',
 'Yemen',
 '29,825,964',
 '2.28 %',
 '664,042',
 '56',
 '527,970',
 '-30,000',
 '3.8',
 '20',
 '38 %',
 '0.38 %',
 '49',
 'Nepal',
 '29,136,808',
 '1.85 %',
 '528,098',
 '203',
 '143,350',
 '41,710',
 '1.9',
 '25',
 '21 %',
 '0.37 %',
 '50',
 'Venezuela',
 '28,435,940',
 '-0.28 %',
 '-79,889',
 '32',
 '882,050',
 '-653,249',
 '2.3',
 '30',
 'N.A.',
 '0.36 %',
 '51',
 'Madagascar',
 '27,691,018',
 '2.68 %',
 '721,711',
 '48',
 '581,795',
 '-1,500',
 '4.1',
 '20',
 '39 %',
 '0.36 %',
 '52',
 'Cameroon',
 '26,545,863',
 '2.59 %',
 '669,483',
 '56',
 '472,710',
 '-4,800',
 '4.6',
 '19',
 '56 %',
 '0.34 %',
 '53',
 "Côte d'Ivoire",
 '26,378,274',
 '2.57 %',
 '661,730',
 '83',
 '318,000',
 '-8,000',
 '4.7',
 '19',
 '51 %',
 '0.34 %',
 '54',
 'North Korea',
 '25,778,816',
 '0.44 %',
 '112,655',
 '214',
 '120,410',
 '-5,403',
 '1.9',
 '35',
 '63 %',
 '0.33 %',
 '55',
 'Australia',
 '25,499,884',
 '1.18 %',
 '296,686',
 '3',
 '7,682,300',
 '158,246',
 '1.8',
 '38',
 '86 %',
 '0.33 %',
 '56',
 'Niger',
 '24,206,644',
 '3.84 %',
 '895,929',
 '19',
 '1,266,700',
 '4,000',
 '7.0',
 '15',
 '17 %',
 '0.31 %',
 '57',
 'Taiwan',
 '23,816,775',
 '0.18 %',
 '42,899',
 '673',
 '35,410',
 '30,001',
 '1.2',
 '42',
 '79 %',
 '0.31 %',
 '58',
 'Sri Lanka',
 '21,413,249',
 '0.42 %',
 '89,516',
 '341',
 '62,710',
 '-97,986',
 '2.2',
 '34',
 '18 %',
 '0.27 %',
 '59',
 'Burkina Faso',
 '20,903,273',
 '2.86 %',
 '581,895',
 '76',
 '273,600',
 '-25,000',
 '5.2',
 '18',
 '31 %',
 '0.27 %',
 '60',
 'Mali',
 '20,250,833',
 '3.02 %',
 '592,802',
 '17',
 '1,220,190',
 '-40,000',
 '5.9',
 '16',
 '44 %',
 '0.26 %',
 '61',
 'Romania',
 '19,237,691',
 '-0.66 %',
 '-126,866',
 '84',
 '230,170',
 '-73,999',
 '1.6',
 '43',
 '55 %',
 '0.25 %',
 '62',
 'Malawi',
 '19,129,952',
 '2.69 %',
 '501,205',
 '203',
 '94,280',
 '-16,053',
 '4.3',
 '18',
 '18 %',
 '0.25 %',
 '63',
 'Chile',
 '19,116,201',
 '0.87 %',
 '164,163',
 '26',
 '743,532',
 '111,708',
 '1.7',
 '35',
 '85 %',
 '0.25 %',
 '64',
 'Kazakhstan',
 '18,776,707',
 '1.21 %',
 '225,280',
 '7',
 '2,699,700',
 '-18,000',
 '2.8',
 '31',
 '58 %',
 '0.24 %',
 '65',
 'Zambia',
 '18,383,955',
 '2.93 %',
 '522,925',
 '25',
 '743,390',
 '-8,000',
 '4.7',
 '18',
 '45 %',
 '0.24 %',
 '66',
 'Guatemala',
 '17,915,568',
 '1.90 %',
 '334,096',
 '167',
 '107,160',
 '-9,215',
 '2.9',
 '23',
 '52 %',
 '0.23 %',
 '67',
 'Ecuador',
 '17,643,054',
 '1.55 %',
 '269,392',
 '71',
 '248,360',
 '36,400',
 '2.4',
 '28',
 '63 %',
 '0.23 %',
 '68',
 'Syria',
 '17,500,658',
 '2.52 %',
 '430,523',
 '95',
 '183,630',
 '-427,391',
 '2.8',
 '26',
 '60 %',
 '0.22 %',
 '69',
 'Netherlands',
 '17,134,872',
 '0.22 %',
 '37,742',
 '508',
 '33,720',
 '16,000',
 '1.7',
 '43',
 '92 %',
 '0.22 %',
 '70',
 'Senegal',
 '16,743,927',
 '2.75 %',
 '447,563',
 '87',
 '192,530',
 '-20,000',
 '4.7',
 '19',
 '49 %',
 '0.21 %',
 '71',
 'Cambodia',
 '16,718,965',
 '1.41 %',
 '232,423',
 '95',
 '176,520',
 '-30,000',
 '2.5',
 '26',
 '24 %',
 '0.21 %',
 '72',
 'Chad',
 '16,425,864',
 '3.00 %',
 '478,988',
 '13',
 '1,259,200',
 '2,000',
 '5.8',
 '17',
 '23 %',
 '0.21 %',
 '73',
 'Somalia',
 '15,893,222',
 '2.92 %',
 '450,317',
 '25',
 '627,340',
 '-40,000',
 '6.1',
 '17',
 '47 %',
 '0.20 %',
 '74',
 'Zimbabwe',
 '14,862,924',
 '1.48 %',
 '217,456',
 '38',
 '386,850',
 '-116,858',
 '3.6',
 '19',
 '38 %',
 '0.19 %',
 '75',
 'Guinea',
 '13,132,795',
 '2.83 %',
 '361,549',
 '53',
 '245,720',
 '-4,000',
 '4.7',
 '18',
 '39 %',
 '0.17 %',
 '76',
 'Rwanda',
 '12,952,218',
 '2.58 %',
 '325,268',
 '525',
 '24,670',
 '-9,000',
 '4.1',
 '20',
 '18 %',
 '0.17 %',
 '77',
 'Benin',
 '12,123,200',
 '2.73 %',
 '322,049',
 '108',
 '112,760',
 '-2,000',
 '4.9',
 '19',
 '48 %',
 '0.16 %',
 '78',
 'Burundi',
 '11,890,784',
 '3.12 %',
 '360,204',
 '463',
 '25,680',
 '2,001',
 '5.5',
 '17',
 '14 %',
 '0.15 %',
 '79',
 'Tunisia',
 '11,818,619',
 '1.06 %',
 '123,900',
 '76',
 '155,360',
 '-4,000',
 '2.2',
 '33',
 '70 %',
 '0.15 %',
 '80',
 'Bolivia',
 '11,673,021',
 '1.39 %',
 '159,921',
 '11',
 '1,083,300',
 '-9,504',
 '2.8',
 '26',
 '69 %',
 '0.15 %',
 '81',
 'Belgium',
 '11,589,623',
 '0.44 %',
 '50,295',
 '383',
 '30,280',
 '48,000',
 '1.7',
 '42',
 '98 %',
 '0.15 %',
 '82',
 'Haiti',
 '11,402,528',
 '1.24 %',
 '139,451',
 '414',
 '27,560',
 '-35,000',
 '3.0',
 '24',
 '57 %',
 '0.15 %',
 '83',
 'Cuba',
 '11,326,616',
 '-0.06 %',
 '-6,867',
 '106',
 '106,440',
 '-14,400',
 '1.6',
 '42',
 '78 %',
 '0.15 %',
 '84',
 'South Sudan',
 '11,193,725',
 '1.19 %',
 ...]

In [17]:
list1=list[0:len(list):12]
list2=list[1:len(list):12]
list3=list[2:len(list):12]
list4=list[3:len(list):12]
list5=list[4:len(list):12]
list6=list[5:len(list):12]
list7=list[6:len(list):12]
list8=list[7:len(list):12]
list9=list[8:len(list):12]
list10=list[9:len(list):12]
list11=list[10:len(list):12]
list12=list[11:len(list):12]
print(len(list1),len(list2),len(list3),len(list4),len(list5),len(list6),len(list7),len(list8),len(list9),len(list10),len(list11),len(list12))

235 235 235 235 235 235 235 235 235 235 235 235

In [13]:
# Creating Dataframe
df=pd.DataFrame({})
df["SR NO"]=list1
df["COUNTRY"]=list2
df["POPULATION"]=list3
df["YEARLY CHANGE"]=list4
df["NET CHANGE"]=list5
df["DENSITY(P/Km)"]=list6
df["LAND AREA(Km)"]=list7
df["MIGRANTS"]=list8
df["FERT RATE"]=list9
df["MED AGE"]=list10
df["URBAN POP"]=list11
df["WORLD SHARE"]=list12
df

,SR NO,COUNTRY,POPULATION,YEARLY CHANGE,NET CHANGE,DENSITY(P/Km),LAND AREA(Km),MIGRANTS,FERT RATE,MED AGE,URBAN POP,WORLD SHARE
0,1,China,"1,439,323,776",0.39 %,"5,540,090",153,"9,388,211","-348,399",1.7,38,61 %,18.47 %
1,2,India,"1,380,004,385",0.99 %,"13,586,631",464,"2,973,190","-532,687",2.2,28,35 %,17.70 %
2,3,United States,"331,002,651",0.59 %,"1,937,734",36,"9,147,420","954,806",1.8,38,83 %,4.25 %
3,4,Indonesia,"273,523,615",1.07 %,"2,898,047",151,"1,811,570","-98,955",2.3,30,56 %,3.51 %
4,5,Pakistan,"220,892,340",2.00 %,"4,327,022",287,"770,880","-233,379",3.6,23,35 %,2.83 %
...,...,...,...,...,...,...,...,...,...,...,...,...
230,231,Montserrat,"4,992",0.06 %,3,50,100,,N.A.,N.A.,10 %,0.00 %
231,232,Falkland Islands,"3,480",3.05 %,103,0,"12,170",,N.A.,N.A.,66 %,0.00 %
232,233,Niue,"1,626",0.68 %,11,6,260,,N.A.,N.A.,46 %,0.00 %
233,234,Tokelau,"1,357",1.27 %,17,136,10,,N.A.,N.A.,0 %,0.00 %
234,235,Holy See,801,0.25 %,2,"2,003",0,,N.A.,N.A.,N.A.,0.00 %

In [14]:
# converting data into CSV
df.to_csv(r"C:\Users\parth\OneDrive\Desktop\parth\web1.csv")

In [15]:
# Connecting dataframe to mysql
import pymysql as cn
con1=cn.connect(host="localhost",user="root",database="webscrapping",password="root")
print("Connection Created Succesfully")

Connection Created Succesfully